### PR TITLE
Add common file extensions

### PR DESCRIPTION
**Pull request by omrilotan**
- [x] mjs - [ECMAScript Modules](https://nodejs.org/api/esm.html#esm_enabling)
- [x] tsx - [TypeScript JSX](https://www.typescriptlang.org/docs/handbook/jsx.html)

Documentation screenshots:

| 
| -

| 
| -

### CODE REVIEW

**Comment by mikermcneil** [comment]
lgtm

**Review by mikermcneil — APPROVED** [review]

**Comment by luislobo** [comment]
Thank you @omrilotan!

I like the linking you did on the README.md file. Would you be kind to add the other extension links?

Can be on this PR or a new one.

**Comment by omrilotan** [comment]
@luislobo Most of them have links in the title. For example, all CoffeeScript file extensions have the same link, which is specified in the list title. So I'm not sure there's a need to add individual links for them.

**Comment by luislobo** [comment]
@omrilotan Makes sense

**Pull request merged**
